### ISSUE TITLE
Crash with Ping!

### ISSUE THREAD

**Issue by jiaoliao946** [CleanroomMC/Cleanroom#129]
### Cleanroom Version

15.24.0.3039

### Java Version

Java 21

### Graphics Card Vendor

Intel iGPU

### Bug Report

Crash when constructing mods.
```
net.minecraftforge.fml.common.LoaderException: chatping Failed to load new mod instance.
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:606)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:85)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:142)
	at com.google.common.eventbus.Subscriber.lambda$dispatchEvent$0(Subscriber.java:71)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:68)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:111)
	at com.google.common.eventbus.EventBus.post(EventBus.java:270)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:303)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:281)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:85)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:142)
	at com.google.common.eventbus.Subscriber.lambda$dispatchEvent$0(Subscriber.java:71)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:68)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:111)
	at com.google.common.eventbus.EventBus.post(EventBus.java:270)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:217)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:596)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:231)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at top.outlands.foundation.LaunchHandler.launch(LaunchHandler.java:119)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at top.outlands.foundation.boot.Foundation.main(Foundation.java:41)
Caused by: java.lang.InstantiationException: santa.ping.Ping
	at java.base/java.lang.Class.newInstance(Class.java:719)
	at net.minecraftforge.fml.common.ILanguageAdapter$JavaAdapter.getNewInstance(ILanguageAdapter.java:46)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:601)
	... 32 more
Caused by: java.lang.NoSuchMethodException: santa.ping.Ping.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3761)
	at java.base/java.lang.Class.newInstance(Class.java:706)
	... 34 more

No Mixin Metadata is found in the Stacktrace.
```

### Mod List

[ping-1.9-3.0.9.jar](https://www.curseforge.com/minecraft/mc-mods/chat-ping)

### MMC Instance Notes

none

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Please install [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1)
