### ISSUE TITLE
Crash with Great Scrollable Tooltips

### ISSUE THREAD

**Issue by jiaoliao946** [CleanroomMC/Cleanroom#147]
### Cleanroom Version

0.2.1-alpha

### Java Version

Java 21

### Graphics Card Vendor

Intel iGPU

### Bug Report

Crash when waiting for the game to launch
```
[08:20:42] [main/INFO]: Calling tweak online.flowerinsnow.greatscrollabletooltips.tweaker.GreatScrollableTooltipsTweaker@7134b8a7
[08:20:42] [main/FATAL]: Unable to launch
java.lang.IllegalArgumentException: URI is not hierarchical
	at java.base/java.io.File.<init>(File.java:420) ~[?:?]
	at online.flowerinsnow.greatscrollabletooltips.tweaker.GreatScrollableTooltipsTweaker.injectIntoClassLoader(GreatScrollableTooltipsTweaker.java:35) ~[GreatScrollableTooltipsTweaker.class:4.2.0]
	at top.outlands.foundation.LaunchHandler.launch(LaunchHandler.java:103) [LaunchHandler.class:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at top.outlands.foundation.boot.Foundation.main(Foundation.java:41) [foundation-0.13.2.jar:?]
```

### Mod List

[great-scrollable-tooltips-4.2.0.jar](https://modrinth.com/mod/great-scrollable-tooltips/version/4.2.0)

### MMC Instance Notes

None

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Add `online.flowerinsnow.greatscrollabletooltips.tweaker.GreatScrollableTooltipsTweaker` to getCodeSource() list in fugue.cfg

**Comment by Romz24** [comment]
@kappa-maintainer 

```
[09:07:11] [main/INFO] [Foundation]: Calling tweak cn.flowerinsnow.greatscrollabletooltips.tweaker.GreatScrollableTooltipsTweaker@46b5f061
[09:07:11] [main/FATAL] [Foundation]: Unable to launch
java.lang.IllegalArgumentException: URI is not hierarchical
	at java.io.File.<init>(File.java:420)
	at cn.flowerinsnow.greatscrollabletooltips.tweaker.GreatScrollableTooltipsTweaker.injectIntoClassLoader(GreatScrollableTooltipsTweaker.java:35)
	at top.outlands.foundation.LaunchHandler.launch(LaunchHandler.java:107)
	at top.outlands.foundation.boot.Foundation.main(Foundation.java:42)
	at com.cleanroommc.relauncher.wrapper.RelaunchMainWrapper.main(RelaunchMainWrapper.java:20)
```

It seems the issue is still present. I checked, and the line you mentioned is already present in the fugue.cfg file.

**Comment by Romz24** [comment]
Mod version: great-scrollable-tooltips-4.3.0+forge.jar

**Comment by kappa-maintainer** [comment]
Have you added that line?

**Comment by Romz24** [comment]
@kappa-maintainer 

This line is already present by default.
I tested it on `great-scrollable-tooltips-4.2.0.jar` and everything works, but the current version, `great-scrollable-tooltips-4.3.0+forge.jar`, prevents the game from launching and causes it to crash.

<img width="650" height="266" alt="Image" src="https://github.com/user-attachments/assets/c789220f-6d35-42cf-a909-614ffabcc1ed" />

**Comment by kappa-maintainer** [comment]
The new version changed  its package
The new line is
`cn.flowerinsnow.greatscrollabletooltips.tweaker.GreatScrollableTooltipsTweaker`

**Comment by Xplodin** [comment]
I changed the line and it still crashes with the same error

**Comment by kappa-maintainer** [comment]
Post your crash report

**Comment by Xplodin** [comment]
```
[main/FATAL] [Foundation]: Unable to launch
java.lang.IllegalArgumentException: URI is not hierarchical
	at java.io.File.<init>(File.java:425)
	at cn.flowerinsnow.greatscrollabletooltips.tweaker.GreatScrollableTooltipsTweaker.injectIntoClassLoader(GreatScrollableTooltipsTweaker.java:35)
	at top.outlands.foundation.LaunchHandler.launch(LaunchHandler.java:107)
	at top.outlands.foundation.boot.Foundation.main(Foundation.java:42)
	at com.cleanroommc.relauncher.wrapper.RelaunchMainWrapper.main(RelaunchMainWrapper.java:20)

```

cn.flowerinsnow.greatscrollabletooltips.tweaker.GreatScrollableTooltipsTweaker
^in fugue

**Comment by kappa-maintainer** [comment]
Reset fugue config with latest version
