### ISSUE TITLE
IC2patcher uses removed Java class, causing crash

### ISSUE THREAD

**Issue by ZZZank** [CleanroomMC/Cleanroom#16]
```
[08:05:45] [main/FATAL] [Bouncepad]: Unable to launch
java.lang.NoClassDefFoundError: java/util/jar/Pack200
	at mods.su5ed.ic2patcher.asm.BinPatchManager.setup(BinPatchManager.java:191) ~[BinPatchManager.class:?]
	at mods.su5ed.ic2patcher.asm.PatcherFMLPlugin.injectData(PatcherFMLPlugin.java:25) ~[PatcherFMLPlugin.class:?]
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:153) ~[cleanroom-15.24.0.3020.jar:?]
	at com.cleanroommc.bouncepad.Bouncepad.launch(Bouncepad.java:145) [bouncepad-0.4.11-cursed.jar:?]
	at com.cleanroommc.bouncepad.Bouncepad.main(Bouncepad.java:42) [bouncepad-0.4.11-cursed.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:53) [JavaWrapper.jar:?]
Caused by: java.lang.ClassNotFoundException: java.util.jar.Pack200
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[bouncepad-0.4.11-cursed.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 9 more
```
[latest.log](https://github.com/CleanroomMC/Cleanroom/files/13629745/latest.log)

`java.util.jar.Pack200` is removed in Java14

**Comment by KorewaLidesu** [comment]
Pack200 💀

**Comment by kappa-maintainer** [comment]
IC2patcher seems to use this to avoid copyright problem of patching IC2 directly.
But we have no interset to add another global transformer for one or two mods, please contact IC2patcher's developers to pack the patch in a different format.

**Comment by ZZZank** [comment]
https://github.com/Su5eD/IC2-Patcher/issues/14
