### ISSUE TITLE
BotaniaTweaks uses absent `sun.reflect.Reflection` Class, causing crash

### ISSUE THREAD

**Issue by ZZZank** [CleanroomMC/Cleanroom#17]
I notice that `sun.reflect.Reflection` was moved to `jdk.unsupported` module in Java9, maybe that's why the crash happens. 

[latest.log](https://github.com/CleanroomMC/Cleanroom/files/13636496/latest.log)

```
java.lang.NoClassDefFoundError: sun/reflect/Reflection
	at quaternary.botaniatweaks.modules.shared.lib.GeneratingFlowers$FlowerData.<clinit>(GeneratingFlowers.java:101) ~[GeneratingFlowers$FlowerData.class:?]
	at quaternary.botaniatweaks.modules.shared.lib.GeneratingFlowers.<clinit>(GeneratingFlowers.java:30) ~[GeneratingFlowers.class:?]
	at quaternary.botaniatweaks.asm.tweaks.EverythingCanDecayTweak.computeAffectedClasses(EverythingCanDecayTweak.java:14) ~[EverythingCanDecayTweak.class:?]
	at quaternary.botaniatweaks.asm.tweaks.Tweak.getAffectedClasses(Tweak.java:18) ~[Tweak.class:?]
	at quaternary.botaniatweaks.asm.BotaniaTweakerTransformer.<clinit>(BotaniaTweakerTransformer.java:36) ~[BotaniaTweakerTransformer.class:?]
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method) ~[?:?]
...
```

**Comment by Rongmario** [comment]
Their usages of the `Reflection` class is quite hostile and there was some drama to it. But we'll probably end up redirecting all references from `sun/reflect/Reflection` to `jdk/internal/reflect/Reflection`.

**Comment by baka4n** [comment]
I think it should be possible to reproduce Reflection and then use java.lang.StackWalker?

**Comment by baka4n** [comment]
Or change all of them to StackWalker at the beginning of use

**Comment by Rongmario** [comment]
While `sun/reflect/Reflection` does have `getCallingClass` that is similar to `StackWalker`. Majority of the usages for `sun/reflect/Reflection` is for hiding methods and fields from being able to be accessed via Reflection, a blacklist if you will.

**Comment by kappa-maintainer** [comment]
Now Cleanroom will redirect sun/reflect/Reflection to a custome Reflection class with empty methods (except getCallerClass)

**Comment by kappa-maintainer** [comment]
Forgot to mention: As for BotaniaTweaks just use this fork:
https://github.com/kappa-maintainer/BotaniaTweaks/releases/tag/1.9.2
The mod is adding transformer exclude to prevent any bytecode modification to its Reflection call, so I have to fork one
