### ISSUE TITLE
crash with(and only with) RandomThings installed

### ISSUE THREAD

**Issue by ZZZank** [CleanroomMC/Cleanroom#18]
I's using [3020 version of Cleanroom](https://github.com/CleanroomMC/Cleanroom/actions/runs/7153689580)
The only mod I installed is RandomThings.

[latest.log](https://github.com/CleanroomMC/Cleanroom/files/13661147/latest.log)
[debug.log](https://github.com/CleanroomMC/Cleanroom/files/13661149/debug.log)
I don't know what exactly the reason is, but this part looks sus: 
```
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer lumien.randomthings.asm.ClassTransformer@3e8799f from coremod LoadingPlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260) ~[cleanroom-15.24.0.3020.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:277) ~[bouncepad-0.4.11-cursed.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:173) ~[bouncepad-0.4.11-cursed.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:42) ~[Main.class:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	... 7 more
```

**Comment by kappa-maintainer** [comment]
> Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at lumien.randomthings.asm.CustomClassWriter.<clinit>(CustomClassWriter.java:12) ~[CustomClassWriter.class:?]
	at lumien.randomthings.asm.ClassTransformer.patchWorldClass(ClassTransformer.java:1434) ~[ClassTransformer.class:?]
	at lumien.randomthings.asm.ClassTransformer.transform(ClassTransformer.java:77) ~[ClassTransformer.class:?]

Mods using old classloader need to be forked, I guess

**Comment by kappa-maintainer** [comment]
Fixed in main a while ago, forgot to close
