### ISSUE TITLE
Groovy script error with Nomifactory CEu

### ISSUE THREAD

**Issue by CrossElectronics** [CleanroomMC/Cleanroom#183]
### Cleanroom Version

0.2.2-alpha

### Java Version

Java 21

### Graphics Card Vendor

Intel iGPU

### Bug Report

When loading up the save, an error occurs complaining about groovy script. This issue is exactly same as #116 except I already have the latest cleanroom and fugue.
```
============  GroovyLog  ====  07.08.2024  ============
GroovyScript version: 1.1.1
[12:40:14] [CLIENT/INFO] [nomiceu]: Running scripts in loader 'preInit'
[12:40:36] [CLIENT/INFO] [nomiceu]: Running scripts in loader 'init'
[12:40:38] [CLIENT/INFO] [nomiceu]: Running scripts in loader 'postInit'
[12:40:38] [CLIENT/INFO] [nomiceu]:  - running org.codehaus.groovy.runtime.InvokerHelper$2
[12:40:38] [CLIENT/INFO] [nomiceu]:  - running earlygame
[12:40:38] [CLIENT/ERROR] [nomiceu]: An exception occurred while running scripts. Look at latest.log for a full stacktrace:
	java.lang.NoClassDefFoundError: net/minecraft/item/ItemStack
		at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
		at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3578)
		at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3603)
		at java.base/java.lang.Class.getMethods(Class.java:2185)
		at java.desktop/com.sun.beans.introspect.MethodInfo.get(MethodInfo.java:89)
		at java.desktop/com.sun.beans.introspect.ClassInfo.getMethods(ClassInfo.java:82)
		at java.desktop/java.beans.Introspector.getTargetMethodInfo(Introspector.java:1029)
		at java.desktop/java.beans.Introspector.getBeanInfo(Introspector.java:446)
		at java.desktop/java.beans.Introspector.getBeanInfo(Introspector.java:195)
		at groovy.lang.MetaClassImpl.lambda$addProperties$25(MetaClassImpl.java:3466)
		at java.base/java.security.AccessController.doPrivileged(AccessController.java:571)
		at groovy.lang.MetaClassImpl.doPrivileged(MetaClassImpl.java:3519)
		at groovy.lang.MetaClassImpl.addProperties(MetaClassImpl.java:3466)
		at groovy.lang.MetaClassImpl.reinitialize(MetaClassImpl.java:3448)
		at groovy.lang.MetaClassImpl.initialize(MetaClassImpl.java:3441)
		at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:272)
		at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:314)
		in earlygame.groovy in line 20
		at com.cleanroommc.groovyscript.sandbox.GroovySandbox.runScript(GroovySandbox.java:166)
		at com.cleanroommc.groovyscript.sandbox.GroovyScriptSandbox.runScript(GroovyScriptSandbox.java:169)
		at com.cleanroommc.groovyscript.sandbox.GroovySandbox.loadScripts(GroovySandbox.java:139)

```

### Mod List

Nomifactory CEu 1.7 beta 5c

### MMC Instance Notes

N/A

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Try latest Cleanroom & Fugue from action
