### ISSUE TITLE
cleanroommc not working on vivecraft

### ISSUE THREAD

**Issue by marrrrrrme6** [CleanroomMC/Cleanroom#193]
### Your CleanroomMC Discord Username

marme0532

### Cleanroom Version

0.2.3-alpha+build.0.run.688

### Java Version

Java 21

### Graphics Card Vendor

Intel iGPU

### Bug Report

latestlog: https://mclo.gs/wjYomGr
debuglog: https://mclo.gs/3WFDm24

Although it is not in the log, there was an error like this
```
Exception caught from launcher
java.lang.NoSuchMethodException: no such method: net.minecraft.launchwrapper.Launch.main(String[])void/invokeStatic
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:915)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:994)
	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3750)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:2675)
	at org.prismlauncher.utils.ReflectionUtils.findMainMethod(ReflectionUtils.java:75)
	at org.prismlauncher.utils.ReflectionUtils.findMainMethod(ReflectionUtils.java:88)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:99)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.launchwrapper.Launch.main(java.lang.String[])'
	at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:962)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:991)
	... 7 more
Exiting with ERROR
Minecraft exited with exit code 2.
```

### Mod List

The minimal reproducible mod set is: none

### MMC Instance Notes

This instance is built using Github Action.
Using installer artifact from commit: 96845fc74822969a6473d647aa4047e1a28ff078
Action URL: https://github.com/CleanroomMC/Cleanroom/actions/runs/9480973366

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Your installation seems broken, try to download the 0.2.3-alpha from release page and import it as instance

**Comment by marrrrrrme6** [comment]
I tried reinstalling it but it didn't change anything, but I did find something that might help.
[vivecraft.json](https://github.com/user-attachments/files/16743753/vivecraft.json)

**Comment by kappa-maintainer** [comment]
So it generates a new json for it
Try to remove its json and extract Cleanroom's to the folder, and add 
```
    {
      "name": "com.mtbs3d:minecrift:1.12.2-jrbudda-11-r6",
      "MMC-hint": "local"
    },
    {
      "name": "org.json:json:20140107",
      "url": "http://vivecraft.org/jar/"
    },
    {"name": "net.minecraft:launchwrapper:1.12"},
    {
      "name": "optifine:OptiFine:1.12.2_HD_U_F5_LIB",
      "MMC-hint": "local"
    }
```
to the libraries section (you need to check the format manually)
Also make the tweaker section look like this
```
    "org.vivecraft.tweaker.MinecriftForgeTweaker",
    "net.minecraftforge.fml.common.launcher.FMLTweaker",
    "optifine.OptiFineForgeTweaker"
```

**Comment by marrrrrrme6** [comment]
I tried to make the change but got this error:

https://mclo.gs/z1ngXlg
https://mclo.gs/HiUVViZ

**Comment by kappa-maintainer** [comment]
Try latest Fugue

**Comment by marrrrrrme6** [comment]
First of all, cleanroom doesn't start, so even if I put in the mod it doesn't work.

**Comment by marrrrrrme6** [comment]
To be precise, it does start, but Vivecraft is a standalone mod that starts with top priority, so even if you install Fugue, Vivecraft will load first and then it will throw an error and stop.

**Comment by kappa-maintainer** [comment]
Ah, the tweaker
Then we don't have much option here, you should open an issue on vivecraft repository instead
