### ISSUE TITLE
Cannot start game on Windows 11 ARM64

### ISSUE THREAD

**Issue by ThatStella7922** [CleanroomMC/Cleanroom#206]
### Cleanroom Version

0.2.3-alpha

### Java Version

Java 21

### Graphics Card Vendor

Other (Please Specify)

### Bug Report

MC Log: https://mclo.gs/OGmUPqf

- MMC instance zip imported into PrismLauncher
- Windows 11 ARM64 build 27695
- Snapdragon 8cx Gen 2 CPU
- Adreno 690 iGPU (OpenGL via [Mesa D3D12 driver](https://docs.mesa3d.org/drivers/d3d12.html))

Relevant snippet:
```
[LWJGL] Version: 3.3.4-snapshot+SNAPSHOT
	 OS: Windows 11 v10.0
	JRE: Windows aarch64 21.0.4
	JVM: OpenJDK 64-Bit Server VM v21.0.4+7-LTS by Microsoft
[LWJGL] Loading JNI library: lwjgl3
	Module: org.lwjgl3
	windows/arm64/org/lwjgl3/lwjgl3.dll not found in java.library.path=C:/Users/Stella/AppData/Roaming/PrismLauncher/instances/Cleanroom-MMC-instance-0.2.3-alpha/natives
	lwjgl3.dll not found in java.library.path
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl3.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[16:20:51] [main/FATAL] [Foundation]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at top.outlands.foundation.LaunchHandler.launch(LaunchHandler.java:119) [LaunchHandler.class:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at top.outlands.foundation.boot.Foundation.main(Foundation.java:41) [foundation-0.13.9.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
Caused by: java.lang.UnsatisfiedLinkError: Failed to locate library: lwjgl3.dll
	at org.lwjgl3.system.Library.loadSystem(Library.java:174) ~[Library.class:SNAPSHOT]
	at org.lwjgl3.system.Library.loadSystem(Library.java:64) ~[Library.class:SNAPSHOT]
	at org.lwjgl3.system.Library.<clinit>(Library.java:52) ~[Library.class:SNAPSHOT]
	at org.lwjgl3.glfw.GLFW.<clinit>(GLFW.java:30) ~[GLFW.class:SNAPSHOT]
	at org.lwjgl.Sys.<clinit>(Sys.java:29) ~[Sys.class:?]
	at net.minecraft.client.Minecraft.func_71386_F(Minecraft.java:2969) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:38) ~[Main.class:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	... 8 more
Process exited with code 1.
```
Seems like it cannot find a Windows ARM64 native of your LWJGL.

### Mod List

  [✔] +Fugue-1.12.2-0.16.3
  [🖿] 1.12 (folder)
  [✔] scalar-1.12.2-2.11.1

### MMC Instance Notes

Nothing in there and I did import the MMC instance zip into prismlauncher.

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by KorewaLidesu** [comment]
Can you using PolyMC instead and see if this work?

**Comment by KorewaLidesu** [comment]
Fixed in https://github.com/CleanroomMC/CleanroomMMC/commit/4d9ad14912e7c4ffe54a62b7f9d94169984941b9
