### ISSUE TITLE
Crash with Logistics Pipes in FTB Interactions Remastered 1.3.0

### ISSUE THREAD

**Issue by JuiceyBeans** [CleanroomMC/Cleanroom#208]
### Your CleanroomMC Discord Username

juiceybeans

### Cleanroom Version

0.2.3-alpha

### Java Version

Java 21

### Graphics Card Vendor

AMD iGPU

### Bug Report

---- Minecraft Crash Report ----
// Lolis deobfuscated this stacktrace using MCP's stable-39 mappings.
// Why did you do that?

Time: 2024-09-23 13:37:52 BST
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Logistics Pipes (logisticspipes)
Caused by: java.lang.ClassNotFoundException: logisticspipes.network.guis.module.inhand.SneakyModuleInHandGuiProvider
    at top.outlands.foundation.boot.ActualClassLoader.findClass(ActualClassLoader.java:259)
    at top.outlands.foundation.boot.ActualClassLoader.loadClass(ActualClassLoader.java:266)
    at logisticspipes.utils.StaticResolverUtil.lambda$null$0(StaticResolverUtil.java:35)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
    at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1715)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
    at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960)
    at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934)
    at java.util.stream.AbstractTask.compute(AbstractTask.java:327)
    at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.lang.IllegalArgumentException: logisticspipes.network.guis.module.inhand
    at java.lang.ClassLoader.definePackage(ClassLoader.java:2239)
    at java.net.URLClassLoader.definePackage(URLClassLoader.java:589)
    at top.outlands.foundation.boot.ActualClassLoader.findClass(ActualClassLoader.java:206)
    ... 15 more

### Mod List

FTB Interactions Remastered 1.3.0

### MMC Instance Notes

N/A

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Try latest Fugue from action

**Comment by PinkDisorder** [comment]
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Logistics Pipes (logisticspipes)
9 | Caused by: java.lang.ClassNotFoundException: logisticspipes.network.packets.debuggui.DebugPanelOpen
10 | at top.outlands.foundation.boot.ActualClassLoader.findClass(ActualClassLoader.java:259)
11 | at top.outlands.foundation.boot.ActualClassLoader.loadClass(ActualClassLoader.java:266)
12 | at logisticspipes.utils.StaticResolverUtil.lambda$null$0(StaticResolverUtil.java:35)
13 | at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
14 | at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1715)
15 | at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
16 | at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
17 | at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960)
18 | at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934)
19 | at java.util.stream.AbstractTask.compute(AbstractTask.java:327)
20 | at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
21 | at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
22 | at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
23 | at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
24 | at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
25 | at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
26 | Caused by: java.lang.IllegalArgumentException: logisticspipes.network.packets.debuggui
27 | at java.lang.ClassLoader.definePackage(ClassLoader.java:2239)
28 | at java.net.URLClassLoader.definePackage(URLClassLoader.java:589)
29 | at top.outlands.foundation.boot.ActualClassLoader.findClass(ActualClassLoader.java:206)
30 | ... 15 more
```

unfortunately the error cuts off at the `15 more`

**Comment by MrLuxALot** [comment]
Have the same issue on latest Cleanroom and Fugue with the same pack. The crash seems to be related to LibrarianLib, bc my crash changed after the first logistics crash log, even though i changed nothing.
[crash-2024-11-25_20.16.52-client.txt](https://github.com/user-attachments/files/17908179/crash-2024-11-25_20.16.52-client.txt)

**Comment by kappa-maintainer** [comment]
@MrLuxALot 
Use latest Cleanroom & latest Fugue (0.17.x)
Use LibrarianLib-Continuous

**Comment by MrLuxALot** [comment]
Well, it fixed it for me ty

**Comment by MrLuxALot** [comment]
Modded minecraft never disappoints when it comes to crashing hehe. Basically it works to load up but sometimes it just doesnt and crashes.
[crash-2024-11-26_21.44.39-client.txt](https://github.com/user-attachments/files/17925610/crash-2024-11-26_21.44.39-client.txt)

**Comment by kappa-maintainer** [comment]
Try new Fugue build from action
https://github.com/CleanroomMC/Fugue/actions/runs/12041146708

**Comment by MrLuxALot** [comment]
It worked for now, maybe it will crash it feels like it

**Comment by kappa-maintainer** [comment]
In theory we could pre-define every packages under `network`, but I believe this cursed custom loading has its limit

**Comment by kappa-maintainer** [comment]
Latest Fugue should have patched this
