### ISSUE TITLE
game crash when Open to lan

### ISSUE THREAD

**Issue by edgeless-player** [CleanroomMC/Cleanroom#227]
### Cleanroom Version

0.2.3-alpha

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

[latest.log](https://github.com/user-attachments/files/17435144/latest.log)

[debug.log](https://github.com/user-attachments/files/17435141/debug.log)

### Mod List

	| State  | ID            | Version       | Source                    | Signature |
	|:------ |:------------- |:------------- |:------------------------- |:--------- |
	| LCHIJA | minecraft     | 1.12.2        | minecraft.jar             | None      |
	| LCHIJA | mcp           | 9.42          | minecraft.jar             | None      |
	| LCHIJA | configanytime | 3.0           | cleanroom-0.2.3-alpha.jar | None      |
	| LCHIJA | cleanroom     | 0.2.3-alpha   | cleanroom-0.2.3-alpha.jar | None      |
	| LCHIJA | FML           | 8.0.99.99     | cleanroom-0.2.3-alpha.jar | None      |
	| LCHIJA | forge         | 14.23.5.2860  | cleanroom-0.2.3-alpha.jar | None      |
	| LCHIJA | mixinbooter   | 10.0          | cleanroom-0.2.3-alpha.jar | None      |
	| LCHIJA | fugue         | 1.12.2-0.16.3 | +Fugue-1.12.2-0.16.3.jar  | None      |
	| UD     | scalar        | 2.11.1        | minecraft.jar             | None      |

### MMC Instance Notes

no

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by ZZZank** [comment]
notes for maintainers if you dont want to download and scroll through throusands of lines in `latest.log`:

```
java.lang.StackOverflowError: Updating screen events
	at com.ibm.icu.impl.SoftCache.getInstance(SoftCache.java:39)
	at com.ibm.icu.impl.ICUResourceBundleReader.getReader(ICUResourceBundleReader.java:365)
	at com.ibm.icu.impl.ICUResourceBundle.createBundle(ICUResourceBundle.java:1007)
	at com.ibm.icu.impl.ICUResourceBundle.instantiateBundle(ICUResourceBundle.java:876)
	at com.ibm.icu.impl.ICUResourceBundle.instantiateBundle(ICUResourceBundle.java:895)
	at com.ibm.icu.impl.ICUResourceBundle.instantiateBundle(ICUResourceBundle.java:895)
	at com.ibm.icu.impl.ICUResourceBundle.instantiateBundle(ICUResourceBundle.java:895)
	at com.ibm.icu.impl.ICUResourceBundle.instantiateBundle(ICUResourceBundle.java:895)
	at com.ibm.icu.impl.ICUResourceBundle.instantiateBundle(ICUResourceBundle.java:895)
	at com.ibm.icu.impl.ICUResourceBundle.instantiateBundle(ICUResourceBundle.java:895)
...
```
and
```
-- Affected screen --
Details:
	Screen name: ~~ERROR~~ NullPointerException: Cannot invoke "Object.getClass()" because "this.this$0.field_71462_r" is null
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1742)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at top.outlands.foundation.LaunchHandler.launch(LaunchHandler.java:119)
...
```
`this.this$0.field_71462_r` is `MinecraftServer.4.currentScreen`, and the first three methods are:
```
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1742)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.run(Minecraft.java:398)
```

**Comment by kappa-maintainer** [comment]
What's your launcher

**Comment by kappa-maintainer** [comment]
No respond for 2 months
