### ISSUE TITLE
VLCJ incompat in java 23

### ISSUE THREAD

**Issue by AnasDevO** [CleanroomMC/Cleanroom#234]
### Your CleanroomMC Discord Username

thermonuclear_minecraft_engineer

### Cleanroom Version

[0.2.3-alpha+build.30.run.759]

### Java Version

Java 23

### Graphics Card Vendor

NVidia

### Bug Report

When using the mod Little Frames in java 23, put down a creative frame; VLCJ invocation fails with the following error:
```
java.lang.Error: Invalid memory access
	at uk.co.caprica.vlcj.binding.LibVlc.libvlc_media_subitems(Native Method) ~[LibVlc.class:?]
	at uk.co.caprica.vlcj.player.base.SubitemApi.changeMedia(SubitemApi.java:108) ~[SubitemApi.class:?]
	at uk.co.caprica.vlcj.player.base.MediaApi.applyMedia(MediaApi.java:426) ~[MediaApi.class:?]
	at uk.co.caprica.vlcj.player.base.MediaApi.changeMedia(MediaApi.java:405) ~[MediaApi.class:?]
	at uk.co.caprica.vlcj.player.base.MediaApi.prepare(MediaApi.java:85) ~[MediaApi.class:?]
	at uk.co.caprica.vlcj.player.base.MediaApi.start(MediaApi.java:113) ~[MediaApi.class:?]
	at team.creative.littleframes.client.display.FrameVideoDisplay.lambda$new$0(FrameVideoDisplay.java:182) ~[FrameVideoDisplay.class:?]
	at java.base/java.lang.Thread.run(Thread.java:1575) [?:?]
```
This is unexpected behavior, since it doesnt happen in java 22

### Mod List

- Little Tiles (latest)
- Little-frames-no-watermedia (latest)

### MMC Instance Notes

This instance is built using Github Action.
Using installer artifact from commit: ea9fd215009abb2d3ef90b0143af88c183b115a7
Action URL: https://github.com/CleanroomMC/Cleanroom/actions/runs/11647856654

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
Looks like a problem of VLCJ, not really something we can patch

**Comment by KorewaLidesu** [comment]
Report this to [LittleFrames](https://github.com/CreativeMD/LittleFrames) instead.
