### ISSUE TITLE
`NoSuchMethodError` when using Charset

### ISSUE THREAD

**Issue by ZZZank** [CleanroomMC/Cleanroom#24]
Only one mod (Charset Lib) is needed to reproduce this crash.

[latest.log](https://github.com/CleanroomMC/Cleanroom/files/13802747/latest.log)
```
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodError: 'java.lang.Object com.google.common.graph.ValueGraph.edgeValue(java.lang.Object, java.lang.Object)'
	at pl.asie.charset.lib.loader.ModuleLoader.passEventWithProgress(ModuleLoader.java:563)
	at pl.asie.charset.ModCharset.preInit(ModCharset.java:154)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:85)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:142)
...
```

**Comment by kappa-maintainer** [comment]
Guava update has made this return an optional
I will update MDK and try to fix this soon

**Comment by kappa-maintainer** [comment]
Just updated MDK, will try to fix charset

**Comment by kappa-maintainer** [comment]
Couldn't find this on ModuleLoader class ... what version of Charset you are using?

**Comment by kappa-maintainer** [comment]
Ah, I figured it out

**Comment by kappa-maintainer** [comment]
Fixed in Fugue, you can get the jar here:
https://github.com/CleanroomMC/Fugue/actions/runs/7398950444

**Comment by ZZZank** [comment]
Thanks for your fast move! Should I leave this issue open or just close it with an  `has workaround` label

**Comment by KorewaLidesu** [comment]
Close as resolved.

**Comment by kappa-maintainer** [comment]
I will call it a long term workaround until someone fork Charset since we don't plan to fork that many mods.
