### ISSUE TITLE
0.2.4-alpha crashes with JEID

### ISSUE THREAD

**Issue by magikorb** [CleanroomMC/Cleanroom#248]
### Your CleanroomMC Discord Username

libtard.so.6

### Cleanroom Version

0.2.4-alpha

### Java Version

Java 21

### Graphics Card Vendor

AMD iGPU

### Bug Report

Crashes with _only_  JEID, Fugue and Scalar installed. Removing the latter two produce the same result.
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinBooter (cleanroom-0.2.4-alpha.jar)
  JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-55.jar)
  ScalarLoadingPlugin (scalar-1.12.2-2.11.1.jar)
  Fugue (+Fugue-1.12.2-0.17.1.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 2024-11-25 18:52
Description: Initializing game

java.lang.NoSuchMethodError: 'java.util.List net.minecraft.launchwrapper.LaunchClassLoader.getTransformers()'
	at net.minecraftforge.fml.common.Loader.handler$zza000$unknown_owner$beforeConstructingMods(Loader.java:1133)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:599)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at top.outlands.foundation.LaunchHandler.launch(LaunchHandler.java:119)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at top.outlands.foundation.boot.Foundation.main(Foundation.java:41)

(MixinBooter) Mixins in Stacktrace:
	net.minecraftforge.fml.common.Loader:
		org.dimdev.jeid.mixin.init.MixinLoader (mixins.jeid.init.json)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.fml.common.Loader.handler$zza000$unknown_owner$beforeConstructingMods(Loader.java:1133)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:599)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at top.outlands.foundation.LaunchHandler.launch(LaunchHandler.java:119)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at top.outlands.foundation.boot.Foundation.main(Foundation.java:41)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Cleanroom Version: 0.2.4-alpha
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.4, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 179672560 bytes (171 MB) / 364904448 bytes (348 MB) up to 7977566208 bytes (7608 MB)
	JVM Flags: 1 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Cleanroom 0.2.4-alpha 10 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID            | Version       | Source                     | Signature |
	|:----- |:------------- |:------------- |:-------------------------- |:--------- |
	| L     | minecraft     | 1.12.2        | minecraft.jar              | None      |
	| L     | mcp           | 9.42          | minecraft.jar              | None      |
	| L     | configanytime | 3.0           | cleanroom-0.2.4-alpha.jar  | None      |
	| L     | cleanroom     | 0.2.4-alpha   | cleanroom-0.2.4-alpha.jar  | None      |
	| L     | FML           | 8.0.99.99     | cleanroom-0.2.4-alpha.jar  | None      |
	| L     | forge         | 14.23.5.2860  | cleanroom-0.2.4-alpha.jar  | None      |
	| L     | mixinbooter   | 10.1          | cleanroom-0.2.4-alpha.jar  | None      |
	| L     | fugue         | 1.12.2-0.17.1 | +Fugue-1.12.2-0.17.1.jar   | None      |
	| L     | jeid          | 1.0.3-55      | JustEnoughIDs-1.0.3-55.jar | None      |
	| UD    | scalar        | 2.11.1        | minecraft.jar              | None      |

	Loaded coremods (and transformers): 
MixinBooter (cleanroom-0.2.4-alpha.jar)
  
JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-55.jar)
  org.dimdev.jeid.JEIDTransformer
ScalarLoadingPlugin (scalar-1.12.2-2.11.1.jar)
  
Fugue (+Fugue-1.12.2-0.17.1.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.0 Compatibility Profile Context 24.7.1.240711' Renderer: 'AMD Radeon(TM) 610M'
	Launched Version: cleanroom-0.2.4-alpha
	LWJGL: 3.3.4-snapshot+SNAPSHOT
	OpenGL: AMD Radeon(TM) 610M GL version 4.6.0 Compatibility Profile Context 24.7.1.240711, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 16x AMD Ryzen 7 7745HX with Radeon Graphics 

### Mod List

jeid
fugue
scalar

### MMC Instance Notes

None

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
The patch for JEID was dropped when moving to Fugue, since REID exists as a full replacement.
