### ISSUE TITLE
java.lang.reflect.InvocationTargetException: null in craftify

### ISSUE THREAD

**Issue by erialsan** [CleanroomMC/Cleanroom#257]
### Your CleanroomMC Discord Username

erialsan

### Cleanroom Version

run798

### Java Version

Java 21

### Graphics Card Vendor

Intel iGPU

### Bug Report

https://mclo.gs/DHVMM34

### Mod List

fugue scalar
craftify

### MMC Instance Notes

Use MMC Instance

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I am using experimental branch and have installed [Scalar](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by Ecdcaeb** [comment]
is it `essential`?
```log
[22:02:34] [main/INFO] [Foundation]: Loading tweak name gg.essential.loader.stage0.EssentialSetupTweaker 186[22:02:34] [main/FATAL] [Foundation]: Unable to launch 187java.lang.reflect.InvocationTargetException: null 188	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74) ~[?:?] 189	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?] 190	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?] 191	at top.outlands.foundation.LaunchHandler.launch(LaunchHandler.java:89) [LaunchHandler.class:?] 192	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] 193	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] 194	at top.outlands.foundation.boot.Foundation.main(Foundation.java:41) [foundation-0.14.1.jar:?] 195	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) [NewLaunch.jar:?] 196	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?] 197	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?] 198Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: object is not an instance of declaring class 199	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:28) ~[EssentialSetupTweaker.class:?] 200	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?] 201	... 9 more 202Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class 203	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.checkReceiver(DirectMethodHandleAccessor.java:197) ~[?:?] 204	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:99) ~[?:?] 205	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] 206	at gg.essential.loader.stage0.EssentialSetupTweaker.addUrlHack(EssentialSetupTweaker.java:81) ~[EssentialSetupTweaker.class:?] 207	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:48) ~[EssentialSetupTweaker.class:?] 208	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26) ~[EssentialSetupTweaker.class:?] 209	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?] 210	... 9 more
```

**Comment by erialsan** [comment]
I didn't put it in Essential. Maybe it's similarly designed.

**Comment by Ecdcaeb** [comment]
Loading tweaker gg.essential.loader.stage0.EssentialSetupTweaker from Craftify-1.12.2-1.16.0-forge.jar

maybe Craftify contains a essential

**Comment by Ecdcaeb** [comment]
yes, it contains an essentialLoader

**Comment by Ecdcaeb** [comment]
Craftify use the structure of essential to load itself.

**Comment by erialsan** [comment]
Crazy design.

**Comment by erialsan** [comment]
You mean Not Planned? I think that's a good idea.

**Comment by erialsan** [comment]
Since the main body is open source but the underlying system is closed source, this issue will be put on hold until a fundamental solution to Essential is found.

**Comment by Ecdcaeb** [comment]
> Since the main body is open source but the underlying system is closed source, this issue will be put on hold until a fundamental solution to Essential is found.

No, it is easy to fix.

**Comment by erialsan** [comment]
amazing

**Comment by Ecdcaeb** [comment]
Try the pr,  get the build from [forked action](https://github.com/Ecdcaeb/Fugue/actions)
I can now boot it up fine, you can try to explore further to make sure it doesn't have any bugs that are caused by the game.
But I think it definitely has, after a while of contact, I think essential is 100 times worse than optifine.

![image](https://github.com/user-attachments/assets/2225d910-0f89-4d92-8296-e0b09b6e2c8b)
