### ISSUE TITLE
Crash with SpongeForge

### ISSUE THREAD

**Issue by PixelmonPRO** [CleanroomMC/Cleanroom#30]
When install Cleanroom [3026 version](https://github.com/CleanroomMC/Cleanroom/actions/runs/7437950950), and install only SpongeForge [7.4.8-RC4142 version](https://repo.spongepowered.org/#browse/browse:maven-releases:org%2Fspongepowered%2Fspongeforge%2F1.12.2-2838-7.4.8-RC4142%2Fspongeforge-1.12.2-2838-7.4.8-RC4142.jar), i get a crash when trying starting server:
```java
net.minecraftforge.fml.common.LoaderException: java.lang.UnsupportedOperationException: SpongeCommon does not have it's own ecosystem, this needs to be mixed into for implementations depending on SpongeCommon
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:384)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.UnsupportedOperationException: SpongeCommon does not have it's own ecosystem, this needs to be mixed into for implementations depending on SpongeCommon
	at org.spongepowered.common.SpongeImplHooks.getImplementationId(SpongeImplHooks.java:554)
	at org.spongepowered.mod.SpongeModMetadata.getSpongeForgeMetadata(SpongeModMetadata.java:118)
	at org.spongepowered.mod.SpongeModMetadata.load(SpongeModMetadata.java:78)
	at org.spongepowered.mod.SpongeModMetadata.get(SpongeModMetadata.java:98)
	at org.spongepowered.mod.SpongeApiModContainer.<init>(SpongeApiModContainer.java:36)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304)
	at java.base/java.lang.Class.newInstance(Class.java:725)
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:379)
	... 6 more
```

Logs: [crash report](https://gist.github.com/PixelmonPRO/13fe2c56b2321a45d9fa63b9d37146b0) / [latest.log](https://gist.github.com/PixelmonPRO/124cbfd0899c0538cb50656be1b2ead8) / [debug.log](https://gist.github.com/PixelmonPRO/dd9543081559f721ebf1816de1c404fd).

**Comment by Rongmario** [comment]
Please revisit this in latest alpha builds of Cleanroom to see if it is fixed.

**Comment by Rongmario** [comment]
Closing in anticipation for the SpongeForge LTS release.

**Comment by D3nnis3n** [comment]
Is there anything been known about the LTS release? The current available one doesn't work, I opened an issue on the LTS tracker, but so far no response.
