### ISSUE TITLE
Crash with OfflineSkins

### ISSUE THREAD

**Issue by PixelmonPRO** [CleanroomMC/Cleanroom#32]
When install Cleanroom [3026 version](https://github.com/CleanroomMC/Cleanroom/actions/runs/7437950950), and install only OfflineSkins [1.12.2-v6 version](https://github.com/zlainsama/OfflineSkins/blob/1.12.2/), i get a crash when trying starting client:
```java
[19:48:53] [main/WARN] [LaunchWrapper]: [Bouncepad] Uppatched ASM5 to ASM9 on class: lain/mods/skins/init/forge/asm/ASMTransformer$transformer003, please port the mod to Cleanroom!
[19:48:53] [main/WARN] [LaunchWrapper]: [Bouncepad] Uppatched ASM5 to ASM9 on class: lain/mods/skins/init/forge/asm/ASMTransformer$transformer002, please port the mod to Cleanroom!
[19:48:53] [main/WARN] [LaunchWrapper]: [Bouncepad] Uppatched ASM5 to ASM9 on class: lain/mods/skins/init/forge/asm/ASMTransformer$transformer001, please port the mod to Cleanroom!
[19:48:53] [main/FATAL] [Bouncepad]: Unable to launch
java.lang.RuntimeException: LZMA.LzmaException: LZMA : Data Error
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:171) ~[cleanroom-15.26.0.3026-universal.jar:?]
	at com.cleanroommc.bouncepad.Bouncepad.launch(Bouncepad.java:145) [bouncepad-0.4.23-cursed.jar:?]
	at com.cleanroommc.bouncepad.Bouncepad.main(Bouncepad.java:42) [bouncepad-0.4.23-cursed.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: LZMA.LzmaException: LZMA : Data Error
	at LZMA.LzmaInputStream.LzmaDecode(LzmaInputStream.java:201) ~[lzma-0.0.1.jar:?]
	at LZMA.LzmaInputStream.fill_buffer(LzmaInputStream.java:233) ~[lzma-0.0.1.jar:?]
	at LZMA.LzmaInputStream.<init>(LzmaInputStream.java:67) ~[lzma-0.0.1.jar:?]
	at lain.mods.skins.init.forge.asm.Setup$2.openStream(Setup.java:42) ~[Setup$2.class:?]
	at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:474) ~[guava-32.1.3-jre.jar:?]
	at com.google.common.io.CharSource.readLines(CharSource.java:371) ~[guava-32.1.3-jre.jar:?]
	at lain.mods.skins.init.forge.asm.Setup.call(Setup.java:45) ~[Setup.class:?]
	at lain.mods.skins.init.forge.asm.Setup.call(Setup.java:17) ~[Setup.class:?]
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:167) ~[cleanroom-15.26.0.3026-universal.jar:?]
	... 8 more
```

https://github.com/zlainsama/OfflineSkins/blob/1.12.2/src/main/java/lain/mods/skins/init/forge/asm/Setup.java
Logs: [latest.log](https://gist.github.com/PixelmonPRO/930318a1c9c5948b7bef41c4b98871ee) / [debug.log](https://gist.github.com/PixelmonPRO/3a580910d65b3103fc4f458f94cf37af).

**Comment by Ecdcaeb** [comment]
Same crash at 0.2.2

**Comment by Ecdcaeb** [comment]
the old forge provide a deobf data `deobfuscation_data-1.12.2.lzma`
but the new provided by cleanroom is just a txt `deobf_data-1.12.2.tsrg`

**Comment by shadl7** [comment]
Use fork: https://github.com/shadl7/OfflineSkinsRevamped
