### ISSUE TITLE
Raw input type mods not working, kills mouse rotation

### ISSUE THREAD

**Issue by ChromaPIE** [CleanroomMC/Cleanroom#47]
```
Exception in thread "getMouseThread" 
[17:00:59] [getMouseThread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:698]: java.lang.NoClassDefFoundError: net/java/games/input/DirectAndRawInputEnvironmentPlugin
[17:00:59] [getMouseThread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:698]: 	at world.maryt.rawinput.RawInputHandler.lambda$getMouse$1(RawInputHandler.java:58)
[17:00:59] [getMouseThread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:698]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[17:00:59] [getMouseThread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:660]: Caused by: java.lang.ClassNotFoundException: net.java.games.input.DirectAndRawInputEnvironmentPlugin
[17:00:59] [getMouseThread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:660]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:225)
[17:00:59] [getMouseThread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:660]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
[17:00:59] [getMouseThread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:660]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[17:00:59] [getMouseThread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:660]: 	... 2 more
[17:00:59] [getMouseThread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:673]: Caused by: java.lang.NullPointerException
```

Tried Raw Input and Raw Input Blessed Edition, happens on both
Works fine on native Forge

Java 21 incompat problem of the mods themselves?

**Comment by kappa-maintainer** [comment]
Try the latest build

**Comment by ChromaPIE** [comment]
pretty sure ive done everything right, using the build from https://github.com/CleanroomMC/CleanroomMMC/actions/runs/7641010018, not working with raw input blessed edition, same error

**Comment by kappa-maintainer** [comment]
Try the latest one, we added jinput lilbrary correctly this time

**Comment by ChromaPIE** [comment]
Not working.
good news it returns a new error:
```
[13:55:48] [getMouseThread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:651]: java.lang.UnsatisfiedLinkError: no jinput-dx8_64 in java.library.path: [DIRECTORY REDACTED]/natives
[13:55:48] [getMouseThread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:651]: 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2458)
[13:55:48] [getMouseThread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:651]: 	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:916)
[13:55:48] [getMouseThread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:651]: 	at java.base/java.lang.System.loadLibrary(System.java:2063)
[13:55:48] [getMouseThread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:651]: 	at net.java.games.input.DirectInputEnvironmentPlugin.lambda$loadLibrary$0(DirectInputEnvironmentPlugin.java:73)
[13:55:48] [getMouseThread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:651]: 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
[13:55:48] [getMouseThread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:651]: 	at net.java.games.input.DirectInputEnvironmentPlugin.loadLibrary(DirectInputEnvironmentPlugin.java:67)
[13:55:48] [getMouseThread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:651]: 	at net.java.games.input.DirectInputEnvironmentPlugin.<clinit>(DirectInputEnvironmentPlugin.java:98)
[13:55:48] [getMouseThread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:651]: 	at net.java.games.input.DirectAndRawInputEnvironmentPlugin.<init>(DirectAndRawInputEnvironmentPlugin.java:45)
[13:55:48] [getMouseThread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:651]: 	at world.maryt.rawinput.RawInputHandler.lambda$getMouse$1(RawInputHandler.java:58)
[13:55:48] [getMouseThread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:651]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[13:55:48] [getMouseThread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:651]: java.lang.UnsatisfiedLinkError: no jinput-raw_64 in java.library.path: [DIRECTORY REDACTED]/natives
[13:55:48] [getMouseThread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:651]: 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2458)
[13:55:48] [getMouseThread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:651]: 	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:916)
[13:55:48] [getMouseThread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:651]: 	at java.base/java.lang.System.loadLibrary(System.java:2063)
[13:55:48] [getMouseThread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:651]: 	at net.java.games.input.RawInputEnvironmentPlugin.lambda$loadLibrary$0(RawInputEnvironmentPlugin.java:73)
[13:55:48] [getMouseThread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:651]: 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
[13:55:48] [getMouseThread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:651]: 	at net.java.games.input.RawInputEnvironmentPlugin.loadLibrary(RawInputEnvironmentPlugin.java:67)
[13:55:48] [getMouseThread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:651]: 	at net.java.games.input.RawInputEnvironmentPlugin.<clinit>(RawInputEnvironmentPlugin.java:98)
[13:55:48] [getMouseThread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:651]: 	at net.java.games.input.DirectAndRawInputEnvironmentPlugin.<init>(DirectAndRawInputEnvironmentPlugin.java:46)
[13:55:48] [getMouseThread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:651]: 	at world.maryt.rawinput.RawInputHandler.lambda$getMouse$1(RawInputHandler.java:58)
[13:55:48] [getMouseThread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:651]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by kappa-maintainer** [comment]
We will figure out how to add natives correctly later, forge's installer is buggy

**Comment by kappa-maintainer** [comment]
Could you test the latest build and see if the built-in raw input is working?

**Comment by tpsrofl** [comment]
> Could you test the latest build and see if the built-in raw input is working?

No dice. I tried the latest commit and the issue is not fixed. Using Cleanroom Loader + Raw Input - Blessed Edition. (I know I am not the person who opened the issue originally but I wanted to help)

**Comment by Rongmario** [comment]
It's now built in, don't use it with raw input mod installed.

**Comment by tpsrofl** [comment]
> It's now built in, don't use it with raw input mod installed.

omg I am so dumb I am sorry. I will retry.

**Comment by tpsrofl** [comment]
It works for me with the latest commit. Mouse rotation works!

**Comment by Rongmario** [comment]
Great news, we'll add this as a config option soon.

**Comment by ChromaPIE** [comment]
i'll be giving it a test later.
also it should be better if we got a list of mods that's incompatible or built-in or stuff or stuff

**Comment by kappa-maintainer** [comment]
We just made this built-in, another built-in mod is wrapfix
As for incompat mods, check Fugue's issue list and mcmod comments.

**Comment by ChromaPIE** [comment]
good to know.
that mod wouldve been dead for days if cleanroom got a warning screen like universal tweaks. i'll make this another issue if needed.
