### ISSUE TITLE
Litematica incompatibility

### ISSUE THREAD

**Issue by mattys1** [CleanroomMC/Cleanroom#55]
## Using: 
- Fugue-1.12.2-0.5.4
- litematica-forge-1.12.2-0.0.0-dev.20191217.195055 from https://masa.dy.fi/mcmods/client_mods/ linked in the litematica github
- malilib-forge-1.12.2-0.10.0-dev.23 also from the link

Game crashes when trying to load and render a schematic. It works fine when selecting an area and also when loading a schematic with disabled graphics rendering in litematica options. Game crashes with and w/o Fugue.

## Steps to reproduce:
- create and import an instance using [CleanroomMMC](https://github.com/CleanroomMC/CleanroomMMC)
- install the mods mentioned above
- select an area and create a schematic
- load the schematic
 
 ## Crash report: 
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FugueLoadingPlugin (Fugue-1.12.2-0.5.4.jar)
  LitematicaCore (litematica-forge-1.12.2-0.0.0-dev.20191217.195055.jar)
  MaLiLibCore (malilib-forge-1.12.2-0.10.0-dev.23.jar)
  MixinBooter (cleanroom-15.24.0.3029-universal.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 2024-02-11 12:50
Description: Unexpected error

java.lang.NoSuchMethodError: 'void com.google.common.util.concurrent.Futures.addCallback(com.google.common.util.concurrent.ListenableFuture, com.google.common.util.concurrent.FutureCallback)'
	at fi.dy.masa.litematica.render.schematic.ChunkRenderWorkerLitematica.processTask(ChunkRenderWorkerLitematica.java:184)
	at fi.dy.masa.litematica.render.schematic.ChunkRenderDispatcherLitematica.updateChunkNow(ChunkRenderDispatcherLitematica.java:176)
	at fi.dy.masa.litematica.render.schematic.RenderGlobalSchematic.func_174970_a(RenderGlobalSchematic.java:400)
	at fi.dy.masa.litematica.render.LitematicaRenderer.piecewisePrepareAndUpdate(LitematicaRenderer.java:297)
	at net.minecraft.client.renderer.EntityRenderer.handler$zzd000$setupAndUpdate(EntityRenderer.java:2174)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1321)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.cleanroommc.bouncepad.Bouncepad.launch(Bouncepad.java:169)
	at com.cleanroommc.bouncepad.Bouncepad.main(Bouncepad.java:42)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

(MixinBooter) Mixins in Stacktrace:
	net.minecraft.client.renderer.EntityRenderer:
		fi.dy.masa.litematica.mixin.MixinEntityRenderer (mixins.litematica.json)
	net.minecraft.client.Minecraft:
		fi.dy.masa.malilib.core.mixin.MixinMinecraft (mixins.malilib.json)
		fi.dy.masa.litematica.mixin.MixinMinecraft (mixins.litematica.json)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at fi.dy.masa.litematica.render.schematic.ChunkRenderWorkerLitematica.processTask(ChunkRenderWorkerLitematica.java:184)
	at fi.dy.masa.litematica.render.schematic.ChunkRenderDispatcherLitematica.updateChunkNow(ChunkRenderDispatcherLitematica.java:176)
	at fi.dy.masa.litematica.render.schematic.RenderGlobalSchematic.func_174970_a(RenderGlobalSchematic.java:400)
	at fi.dy.masa.litematica.render.LitematicaRenderer.piecewisePrepareAndUpdate(LitematicaRenderer.java:297)
	at net.minecraft.client.renderer.EntityRenderer.handler$zzd000$setupAndUpdate(EntityRenderer.java:2174)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1321)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['mattys0008'/2, l='MpServer', x=-514.87, y=4.00, z=641.87]]
	Chunk stats: MultiplayerChunkCache: 529, 529
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-510,4,641), Chunk: (at 2,0,1 in -32,40; contains blocks -512,0,640 to -497,255,655), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Level time: 590 game time, 590 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 40 total; [EntitySlime['Slime'/9283, l='MpServer', x=-552.44, y=4.00, z=643.82], EntitySlime['Slime'/30723, l='MpServer', x=-583.95, y=4.33, z=663.11], EntitySlime['Slime'/32516, l='MpServer', x=-503.20, y=4.00, z=651.29], EntitySheep['Sheep'/72453, l='MpServer', x=-448.50, y=4.00, z=609.50], EntitySheep['Sheep'/72452, l='MpServer', x=-446.50, y=4.00, z=609.50], EntitySlime['Slime'/89028, l='MpServer', x=-548.88, y=4.00, z=604.08], EntityCow['Cow'/72455, l='MpServer', x=-441.50, y=4.00, z=612.50], EntitySheep['Sheep'/72454, l='MpServer', x=-446.42, y=4.00, z=614.34], EntitySlime['Slime'/19918, l='MpServer', x=-447.93, y=4.00, z=577.49], EntitySlime['Slime'/73038, l='MpServer', x=-580.55, y=4.00, z=562.29], EntitySlime['Slime'/96654, l='MpServer', x=-572.07, y=4.00, z=679.89], EntitySlime['Slime'/110862, l='MpServer', x=-579.50, y=4.00, z=719.50], EntitySlime['Slime'/36752, l='MpServer', x=-545.63, y=4.27, z=650.34], EntitySlime['Slime'/38928, l='MpServer', x=-583.70, y=5.25, z=681.14], EntitySlime['Slime'/71380, l='MpServer', x=-530.99, y=4.00, z=574.77], EntityCow['Cow'/72473, l='MpServer', x=-567.50, y=4.00, z=638.50], EntityCow['Cow'/72472, l='MpServer', x=-570.50, y=4.00, z=639.50], EntitySheep['Sheep'/72475, l='MpServer', x=-579.50, y=4.00, z=642.50], EntitySlime['Slime'/98587, l='MpServer', x=-585.22, y=4.00, z=671.27], EntitySlime['Slime'/108315, l='MpServer', x=-592.39, y=4.72, z=659.96], EntityCow['Cow'/72474, l='MpServer', x=-567.50, y=4.00, z=640.50], EntitySlime['Slime'/108316, l='MpServer', x=-590.98, y=4.72, z=661.40], EntitySheep['Sheep'/72479, l='MpServer', x=-527.50, y=4.00, z=562.50], EntitySlime['Slime'/97, l='MpServer', x=-456.99, y=4.00, z=584.75], EntitySlime['Slime'/14506, l='MpServer', x=-536.68, y=4.00, z=592.04], EntitySlime['Slime'/2285, l='MpServer', x=-556.87, y=4.14, z=654.31], EntitySheep['Sheep'/72435, l='MpServer', x=-560.29, y=4.00, z=698.54], EntityCow['Cow'/72434, l='MpServer', x=-550.50, y=4.00, z=698.50], EntityChicken['Chicken'/72437, l='MpServer', x=-550.50, y=4.00, z=703.50], EntitySheep['Sheep'/72436, l='MpServer', x=-552.40, y=4.00, z=698.40], EntitySlime['Slime'/2743, l='MpServer', x=-570.32, y=4.00, z=698.93], EntityHorse['Horse'/72438, l='MpServer', x=-568.50, y=4.00, z=584.50], EntityHorse['Horse'/72441, l='MpServer', x=-569.50, y=4.00, z=592.50], EntityHorse['Horse'/72440, l='MpServer', x=-568.50, y=4.00, z=590.50], EntityPig['Pig'/72443, l='MpServer', x=-567.50, y=4.00, z=587.50], EntityHorse['Horse'/72442, l='MpServer', x=-573.50, y=4.00, z=593.50], EntityPlayerSP['mattys0008'/2, l='MpServer', x=-514.87, y=4.00, z=641.87], EntitySlime['Slime'/124, l='MpServer', x=-574.93, y=4.00, z=695.14], EntitySlime['Slime'/29948, l='MpServer', x=-520.01, y=4.00, z=666.36], EntitySlime['Slime'/55740, l='MpServer', x=-471.17, y=4.80, z=668.76]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2719)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.cleanroommc.bouncepad.Bouncepad.launch(Bouncepad.java:169)
	at com.cleanroommc.bouncepad.Bouncepad.main(Bouncepad.java:42)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1413724152 bytes (1348 MB) / 2097152000 bytes (2000 MB) up to 11542724608 bytes (11008 MB)
	JVM Flags: 43 total; -XX:ThreadPriorityPolicy=1 -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCIProduct -XX:-UnlockExperimentalVMOptions -XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:+AlwaysActAsServerClassMachine -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+UseNUMA -XX:AllocatePrefetchStyle=3 -XX:NmethodSweepActivity=1 -XX:ReservedCodeCacheSize=400M -XX:NonNMethodCodeHeapSize=12M -XX:ProfiledCodeHeapSize=194M -XX:NonProfiledCodeHeapSize=194M -XX:-DontCompileHugeMethods -XX:+PerfDisableSharedMem -XX:+UseFastUnorderedTimeStamps -XX:+UseCriticalJavaThreadPriority -XX:+EagerJVMCI -XX:+UseG1GC -XX:MaxGCPauseMillis=37 -XX:+PerfDisableSharedMem -XX:G1HeapRegionSize=16M -XX:G1NewSizePercent=23 -XX:G1ReservePercent=20 -XX:SurvivorRatio=32 -XX:G1MixedGCCountTarget=3 -XX:G1HeapWastePercent=20 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1RSetUpdatingPauseTimePercent=0 -XX:MaxTenuringThreshold=1 -XX:G1SATBBufferEnqueueingThresholdPercent=30 -XX:G1ConcMarkStepDurationMillis=5.0 -XX:G1ConcRSHotCardLimit=16 -XX:G1ConcRefinementServiceIntervalMillis=150 -XX:GCTimeRatio=99 -XX:+UseLargePages -XX:LargePageSizeInBytes=2m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2000m -Xmx11000m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Cleanroom 14.23.5.0 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID          | Version                   | Source                                                | Signature                                |
	|:------ |:----------- |:------------------------- |:----------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft   | 1.12.2                    | minecraft.jar                                         | None                                     |
	| LCHIJA | mcp         | 9.42                      | minecraft.jar                                         | None                                     |
	| LCHIJA | FML         | 8.0.99.99                 | cleanroom-15.24.0.3029-universal.jar                  | None                                     |
	| LCHIJA | forge       | 14.23.5.0                 | cleanroom-15.24.0.3029-universal.jar                  | None                                     |
	| LCHIJA | mixinbooter | 100.0                     | minecraft.jar                                         | None                                     |
	| LCHIJA | fugue       | 1.12.2-0.5.4              | Fugue-1.12.2-0.5.4.jar                                | None                                     |
	| LCHIJA | malilib     | 0.10.0-dev.23             | malilib-forge-1.12.2-0.10.0-dev.23.jar                | 2b03e1423915a189b8094816baa18f239d576dff |
	| LCHIJA | litematica  | 0.0.0-dev.20191217.195055 | litematica-forge-1.12.2-0.0.0-dev.20191217.195055.jar | 2b03e1423915a189b8094816baa18f239d576dff |

	Loaded coremods (and transformers): 
FugueLoadingPlugin (Fugue-1.12.2-0.5.4.jar)
  com.cleanroommc.transformer.CommonRegistrar$Transformer
LitematicaCore (litematica-forge-1.12.2-0.0.0-dev.20191217.195055.jar)
  
MaLiLibCore (malilib-forge-1.12.2-0.10.0-dev.23.jar)
  
MixinBooter (cleanroom-15.24.0.3029-universal.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 546.33' Renderer: 'NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2'
	Launched Version: 1.12.2
	LWJGL: 3.3.4-snapshot+SNAPSHOT
	OpenGL: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 546.33, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: <unknown>
```

**Comment by erialsan** [comment]
Malilib from Modrinth will improve this.
The same goes for Item scroller, MiniHUD, and Tweakeroo, but Tweakeroo is quite unstable, crashes frequently, and is not compatible with Vintagium.
At least that should cure Litematica.

**Comment by 8MiYile** [comment]
how to download cleanroom-15.24.0.3029 installer?

**Comment by kappa-maintainer** [comment]
Try the latest Fugue build from action
https://github.com/CleanroomMC/Fugue/actions/runs/11103630005
