### ISSUE TITLE
cleanroom 和 ModularUI 不兼容

### ISSUE THREAD

**Issue by abmcar** [CleanroomMC/Cleanroom#92]
### Cleanroom Version

15.24.0.3031

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

从这个构建版本开始 https://github.com/CleanroomMC/CleanroomMMC/actions/runs/8258793580
cleanroom与ModularUI(2.4.3)不再兼容
```
[13:00:10] [main/INFO] [Foundation]: Calling tweak class ModularUI-Core {[]}
[13:00:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:651]: java.lang.reflect.InvocationTargetException
[13:00:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:651]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
[13:00:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:651]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[13:00:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:651]: 	at top.outlands.foundation.boot.Foundation.main(Foundation.java:41)
[13:00:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:651]: 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
[13:00:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:651]: 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
[13:00:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:651]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
[13:00:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:660]: Caused by: java.lang.NoSuchMethodError: 'java.util.List net.minecraft.launchwrapper.LaunchClassLoader.getTransformers()'
[13:00:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:660]: 	at com.cleanroommc.modularui.core.ModularUICore.injectData(ModularUICore.java:43)
[13:00:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:660]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:133)
[13:00:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:660]: 	at top.outlands.foundation.LaunchHandler.launch(LaunchHandler.java:100)
[13:00:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:660]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[13:00:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:660]: 	... 5 more
```
[debug.log](https://github.com/CleanroomMC/Cleanroom/files/14622471/debug.log)

### Mod List

ModularUI-2.4.3

### MMC Instance Notes

prism launcher 8.0

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fixed this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
请使用最新fugue并确保相关类在fugue.cfg的LWTarget下

**Comment by abmcar** [comment]
新版本的cleanroom好像与solar flux reborn也有问题
安装最新fugue后把
tk.zeitheron.solarflux.items.ItemTransferRateUpgrade
放到UUID Patch Target List下也无效(也可能是我放错了？

```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Solar Flux Reborn (solarflux)
Caused by: java.lang.ExceptionInInitializerError
	at tk.zeitheron.solarflux.init.ItemsSF.<clinit>(ItemsSF.java:22)
	at tk.zeitheron.solarflux.SolarFlux.preInit(SolarFlux.java:181)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:85)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:142)
	at com.google.common.eventbus.Subscriber.lambda$dispatchEvent$0(Subscriber.java:71)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:68)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:111)
	at com.google.common.eventbus.EventBus.post(EventBus.java:270)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:279)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:257)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:85)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:142)
	at com.google.common.eventbus.Subscriber.lambda$dispatchEvent$0(Subscriber.java:71)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:68)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:111)
	at com.google.common.eventbus.EventBus.post(EventBus.java:270)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:193)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:251)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at top.outlands.foundation.LaunchHandler.launch(LaunchHandler.java:115)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at top.outlands.foundation.boot.Foundation.main(Foundation.java:41)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.IllegalArgumentException: UUID string too large
	at java.base/java.util.UUID.fromString1(UUID.java:266)
	at java.base/java.util.UUID.fromString(UUID.java:260)
	at tk.zeitheron.solarflux.items.ItemTransferRateUpgrade.<clinit>(ItemTransferRateUpgrade.java:24)
	... 40 more
```

**Comment by kappa-maintainer** [comment]
确实无效，这个没咋测试，估计移植时出毛病了

**Comment by kappa-maintainer** [comment]
好吧，原来真正new UUID的是最下面一行那个类
而且Solar Flux有足足三个类用了有问题的UUID
将这些填进UUID targets就行了
```
tk.zeitheron.solarflux.items.ItemEfficiencyUpgrade
tk.zeitheron.solarflux.items.ItemTransferRateUpgrade
tk.zeitheron.solarflux.items.ItemCapacityUpgrade```
